USE `game`;

DELIMITER $$

-- PHOTOS TRIGGERS

CREATE OR REPLACE TRIGGER `photos_BEFORE_DELETE`
BEFORE DELETE 
ON `photos`
FOR EACH ROW 
BEGIN 
	SIGNAL SQLSTATE VALUE '03999'
	SET MESSAGE_TEXT = 'Delete are restricted.', MYSQL_ERRNO = 999;
END$$

-- ICONS TRIGGERS

CREATE OR REPLACE TRIGGER `icons_BEFORE_DELETE`
BEFORE DELETE 
ON `icons`
FOR EACH ROW 
BEGIN 
	SIGNAL SQLSTATE VALUE '03999'
	SET MESSAGE_TEXT = 'Delete are restricted.', MYSQL_ERRNO = 999;
END$$

-- USER_PROFILES TRIGGERS

CREATE OR REPLACE TRIGGER `user_profiles_BEFORE_DELETE`
BEFORE DELETE 
ON `user_profiles`
FOR EACH ROW 
BEGIN 
	SIGNAL SQLSTATE VALUE '03999'
	SET MESSAGE_TEXT = 'Delete are restricted.', MYSQL_ERRNO = 999;
END$$

-- ADMIN_PROFILES TRIGGERS

CREATE OR REPLACE TRIGGER `admin_profiles_BEFORE_DELETE`
BEFORE DELETE 
ON `admin_profiles`
FOR EACH ROW 
BEGIN 
	SIGNAL SQLSTATE VALUE '03999'
	SET MESSAGE_TEXT = 'Delete are restricted.', MYSQL_ERRNO = 999;
END$$

-- USERS TRIGGERS
CREATE OR REPLACE TRIGGER `users_BEFORE_INSERT`
BEFORE INSERT
ON `users`
FOR EACH ROW 
BEGIN 
	INSERT INTO `user_profiles` SET `firstname` = NULL;
	SET NEW.`profile_id` = LAST_INSERT_ID();
END$$

CREATE OR REPLACE TRIGGER `users_AFTER_INSERT`
AFTER INSERT
ON `users`
FOR EACH ROW 
BEGIN 
	CALL create_accounts(NEW.`id`, NULL);
END$$

CREATE OR REPLACE TRIGGER `users_BEFORE_DELETE`
BEFORE DELETE 
ON `users`
FOR EACH ROW 
BEGIN 
	SIGNAL SQLSTATE VALUE '03999'
	SET MESSAGE_TEXT = 'Delete are restricted.', MYSQL_ERRNO = 999;
END$$

-- ADMINS TRIGGERS

CREATE OR REPLACE TRIGGER `admins_BEFORE_INSERT`
BEFORE INSERT
ON `admins`
FOR EACH ROW 
BEGIN 
	INSERT INTO `admin_profiles` SET `firstname` = NULL;
	SET NEW.`profile_id` = LAST_INSERT_ID();
END$$

CREATE OR REPLACE TRIGGER `admins_AFTER_INSERT`
AFTER INSERT
ON `admins`
FOR EACH ROW 
BEGIN 
	CALL create_accounts(NULL, NEW.`id`);
END$$

CREATE OR REPLACE TRIGGER `admins_BEFORE_DELETE`
BEFORE DELETE 
ON `admins`
FOR EACH ROW 
BEGIN 
	SIGNAL SQLSTATE VALUE '03999'
	SET MESSAGE_TEXT = 'Delete are restricted.', MYSQL_ERRNO = 999;
END$$

-- ACCOUNTS TRIGGERS

CREATE OR REPLACE TRIGGER `accounts_BEFORE_DELETE`
BEFORE DELETE 
ON `accounts`
FOR EACH ROW 
BEGIN 
	SIGNAL SQLSTATE VALUE '03999'
	SET MESSAGE_TEXT = 'Delete are restricted.', MYSQL_ERRNO = 999;
END$$

-- SERVERS TRIGGERS

CREATE OR REPLACE TRIGGER `servers_BEFORE_DELETE`
BEFORE DELETE 
ON `servers`
FOR EACH ROW 
BEGIN 
	SIGNAL SQLSTATE VALUE '03999'
	SET MESSAGE_TEXT = 'Delete are restricted.', MYSQL_ERRNO = 999;
END$$

-- SKILLS TRIGGERS

CREATE OR REPLACE TRIGGER `skills_BEFORE_DELETE`
BEFORE DELETE 
ON `skills`
FOR EACH ROW 
BEGIN 
	SIGNAL SQLSTATE VALUE '03999'
	SET MESSAGE_TEXT = 'Delete are restricted.', MYSQL_ERRNO = 999;
END$$

-- RACES TRIGGERS

CREATE OR REPLACE TRIGGER `races_BEFORE_DELETE`
BEFORE DELETE 
ON `races`
FOR EACH ROW 
BEGIN 
	SIGNAL SQLSTATE VALUE '03999'
	SET MESSAGE_TEXT = 'Delete are restricted.', MYSQL_ERRNO = 999;
END$$

-- PROFESSIONS TRIGGERS

CREATE OR REPLACE TRIGGER `professions_BEFORE_DELETE`
BEFORE DELETE 
ON `professions`
FOR EACH ROW 
BEGIN 
	SIGNAL SQLSTATE VALUE '03999'
	SET MESSAGE_TEXT = 'Delete are restricted.', MYSQL_ERRNO = 999;
END$$

-- CHARACTERISTICS TRIGGERS

CREATE OR REPLACE TRIGGER `characteristics_BEFORE_DELETE`
BEFORE DELETE 
ON `characteristics`
FOR EACH ROW 
BEGIN 
	SIGNAL SQLSTATE VALUE '03999'
	SET MESSAGE_TEXT = 'Delete are restricted.', MYSQL_ERRNO = 999;
END$$

-- PROFESSION_BASE_CHARACTERISTICS TRIGGERS

CREATE OR REPLACE TRIGGER `profession_base_characteristics_BEFORE_DELETE`
BEFORE DELETE 
ON `profession_base_characteristics`
FOR EACH ROW 
BEGIN 
	SIGNAL SQLSTATE VALUE '03999'
	SET MESSAGE_TEXT = 'Delete are restricted.', MYSQL_ERRNO = 999;
END$$

-- PROFESSION_BASE_STATS TRIGGERS

CREATE OR REPLACE TRIGGER `profession_base_stats_BEFORE_DELETE`
BEFORE DELETE 
ON `profession_base_stats`
FOR EACH ROW 
BEGIN 
	SIGNAL SQLSTATE VALUE '03999'
	SET MESSAGE_TEXT = 'Delete are restricted.', MYSQL_ERRNO = 999;
END$$

-- CHARACTER_STATS TRIGGERS

CREATE OR REPLACE TRIGGER `character_stats_BEFORE_DELETE`
BEFORE DELETE 
ON `character_stats`
FOR EACH ROW 
BEGIN 
	SIGNAL SQLSTATE VALUE '03999'
	SET MESSAGE_TEXT = 'Delete are restricted.', MYSQL_ERRNO = 999;
END$$

-- CLANS TRIGGERS

CREATE OR REPLACE TRIGGER `clans_BEFORE_DELETE`
BEFORE DELETE 
ON `clans`
FOR EACH ROW 
BEGIN 
	SIGNAL SQLSTATE VALUE '03999'
	SET MESSAGE_TEXT = 'Delete are restricted.', MYSQL_ERRNO = 999;
END$$

-- ITEM_TYPES TRIGGERS

CREATE OR REPLACE TRIGGER `item_types_BEFORE_DELETE`
BEFORE DELETE 
ON `item_types`
FOR EACH ROW 
BEGIN 
	SIGNAL SQLSTATE VALUE '03999'
	SET MESSAGE_TEXT = 'Delete are restricted.', MYSQL_ERRNO = 999;
END$$

-- ITEM_CHARACTERISTICS TRIGGERS

CREATE OR REPLACE TRIGGER `item_characteristics_BEFORE_DELETE`
BEFORE DELETE 
ON `item_characteristics`
FOR EACH ROW 
BEGIN 
	SIGNAL SQLSTATE VALUE '03999'
	SET MESSAGE_TEXT = 'Delete are restricted.', MYSQL_ERRNO = 999;
END$$

-- ITEMS TRIGGERS

CREATE OR REPLACE TRIGGER `items_BEFORE_DELETE`
BEFORE DELETE 
ON `items`
FOR EACH ROW 
BEGIN 
	SIGNAL SQLSTATE VALUE '03999'
	SET MESSAGE_TEXT = 'Delete are restricted.', MYSQL_ERRNO = 999;
END$$

-- INVENTORIES TRIGGERS

CREATE OR REPLACE TRIGGER `inventories_BEFORE_DELETE`
BEFORE DELETE 
ON `inventories`
FOR EACH ROW 
BEGIN 
	SIGNAL SQLSTATE VALUE '03999'
	SET MESSAGE_TEXT = 'Delete are restricted.', MYSQL_ERRNO = 999;
END$$

-- INVENTORY_ITEMS TRIGGERS

CREATE OR REPLACE TRIGGER `inventory_items_BEFORE_DELETE`
BEFORE DELETE 
ON `inventory_items`
FOR EACH ROW 
BEGIN 
	SIGNAL SQLSTATE VALUE '03999'
	SET MESSAGE_TEXT = 'Delete are restricted.', MYSQL_ERRNO = 999;
END$$

-- CHARACTER_WAREHOUSES TRIGGERS

CREATE OR REPLACE TRIGGER `character_warehouses_BEFORE_DELETE`
BEFORE DELETE 
ON `character_warehouses`
FOR EACH ROW 
BEGIN 
	SIGNAL SQLSTATE VALUE '03999'
	SET MESSAGE_TEXT = 'Delete are restricted.', MYSQL_ERRNO = 999;
END$$

-- CHARACTERS TRIGGERS

CREATE OR REPLACE TRIGGER `characters_BEFORE_DELETE`
BEFORE DELETE 
ON `characters`
FOR EACH ROW 
BEGIN 
	SIGNAL SQLSTATE VALUE '03999'
	SET MESSAGE_TEXT = 'Delete are restricted.', MYSQL_ERRNO = 999;
END$$

CREATE OR REPLACE TRIGGER `characters_BEFORE_INSERT`
BEFORE INSERT 
ON `characters`
FOR EACH ROW 
BEGIN 
	INSERT INTO `inventories`(`free_space`) VALUES 
	(DEFAULT);
	SET NEW.`inventory_id` = LAST_INSERT_ID();

	INSERT INTO `character_warehouses`(`free_space`) VALUES 
	(DEFAULT);
	SET NEW.`character_warehous_id` = LAST_INSERT_ID();
END




